import Pagenotfound from "@/components/Pagenotfound";
export const metadata = {
    title: "منصة  الدكتور",
    description: "Generated by create next app",
  };
  

export default function page404() {
  return (
<>
  <Pagenotfound/>
</>
  )
}
