
import HomePage from "@/components/Home_components/HomePage";
import FeatureSection from "@/components/Home_components/FeatureSection";
import TeacherSection from '@/components/Home_components/TeacherSection'
import GradeSection from "@/components/Home_components/GradesSection";

export const metadata = {
  title: "منصة  الدكتور",
  description: "Generated by create next app",
};

export default function Home() {

  return (
  <>
    <HomePage />
    <FeatureSection />
    <TeacherSection />
    <GradeSection />
  </>
  );
}
